Semi-pointless PR which will create more verbose logs.
Cog-Creators/Red-Lavalink pull request #88
Opened 2021-04-23 17:54 UTC by Drapersniper

+ black with Line length 99 run for free :awesome:

2021-05-17 00:48 UTC, jack1142 requested changes, later dismissed
Reviewed everything except for the alive changes.

2021-05-17 00:48 UTC, jack1142 commented on lavalink/enums.py
> +    DISCONNECTING = 5
Possible breaking change and this is a micro release
```suggestion
    CREATED = 7
    CONNECTING = 0
    READY = 1
    NODE_BUSY = 2
    RECONNECTING = 3
    DISCONNECTING = 4
```

2021-05-17 00:48 UTC, jack1142 commented on lavalink/player_manager.py
> +            f"length={self.current.length if self.current else 0}, node={self.node}>"
```suggestion
            "<Player: "
            f"state={self.state.name}, "
            f"guild={self.guild.name!r} ({self.guild.id}), "
            f"channel={self.channel.name!r} ({self.channel.id}), "
            f"playing={self.is_playing}, paused={self.paused}, volume={self.volume}, "
            f"queue_size={len(self.queue)}, current={self.current}, "
            f"position={self.position}, "
            f"length={self.current.length if self.current else 0}, node={self.node!r}>"
```

2021-05-17 00:48 UTC, jack1142 commented on lavalink/player_manager.py
> +            raise TypeError(f"Cannot move {self} to a different guild.")
Optional, shows the intent more clearly.
```suggestion
            raise TypeError(f"Cannot move {self!r} to a different guild.")
```

2021-05-17 00:48 UTC, jack1142 commented on lavalink/rest_api.py
> +        )
```suggestion
        return (
            "<Track: "
            f"track_identifier={self.track_identifier!r}, "
            f"author={self.author!r}, "
            f"length={self.length}, "
            f"is_stream={self.is_stream}, uri={self.uri!r}, title={self.title!r}>"
        )
```

2021-05-17 00:48 UTC, jack1142 commented on lavalink/rest_api.py
> +            log.debug("Received server disconnected error when player state = %s", self.state)
```suggestion
            log.debug("Received server disconnected error when player state = %s", self.state.name)
```

2021-05-17 00:48 UTC, jack1142 commented on lavalink/__init__.py
> +set_logging_level(20)
The function already has a default value so let's not introduce a magic number here.
```suggestion
set_logging_level()
```

2021-05-17 00:58 UTC, Drapersniper commented on lavalink/player_manager.py
> +            f"queue_size={len(self.queue)}, current={self.current}, "
```suggestion
            f"queue_size={len(self.queue)}, current={self.current!r}, "
```

2021-05-18 22:14 UTC, jack1142 requested changes

2021-05-18 22:14 UTC, Jackenmen commented on lavalink/player_manager.py
>      def __repr__(self):
imo we should add the state of `alive` attr to the repr

Perhaps also connected_at though I'm not sure whether that attr is all that useful for the repr

2021-05-18 22:14 UTC, Jackenmen commented on lavalink/lavalink.py
> +    p.connected_at = datetime.datetime.now(datetime.timezone.utc)
This is already handled by `Player.connect()` which is called by `PlayerManager.create_player()`. Alternatively, `PlayerManager.create_player()` may call `Player.move_to()` but I don't think we want to update this attr in such cases (and if we do, that should be done in `Player.move_to()`)

2021-05-18 22:14 UTC, jack1142 commented on lavalink/player_manager.py
> +        self._alive = True
```suggestion
```

2021-05-18 22:14 UTC, jack1142 commented on lavalink/player_manager.py
> +        self._alive = True
```suggestion
```

2021-05-18 22:14 UTC, jack1142 commented on lavalink/player_manager.py
> +        self._alive = True
```suggestion
```

2021-05-18 22:14 UTC, jack1142 commented on lavalink/player_manager.py
> +        self.connected_at = datetime.datetime.now(datetime.timezone.utc)
Should this really be set to if we haven't connected yet?

2021-05-18 22:34 UTC, jack1142 requested changes

2021-05-18 22:34 UTC, jack1142 commented on lavalink/lavalink.py
> +import datetime
```suggestion
```

2021-05-18 22:36 UTC, jack1142 requested changes

2021-05-18 22:36 UTC, jack1142 commented on lavalink/__init__.py
> +    "all_players",
```suggestion
    "all_players",
    "all_connected_players",
```

2021-05-18 22:37 UTC, jack1142 approved these changes
LGTM

2021-05-18 22:41 UTC, merged